### ISSUE TITLE
Sending Message Problem

### ISSUE THREAD

**Issue by resatkrlc** [yisbug/whatsapp-nodejs#7]
Firstly thanks for your great project. It's ultimate easier than yowsup. Question is, when i am sending message, i get this error:

Nov 20 20:25:56 WA[12172] ERROR: create_session error SignalProtocolAddress { _name: '905421605515', _deviceId: 1 } TypeError: Cannot read property 'version' of null
    at Function.deserialize (D:\node\whatsapp-nodejs-master\node_modules\@privacyresearch\libsignal-protocol-typescript\lib\session-record.js:56:18)
    at SessionBuilder.<anonymous> (D:\node\whatsapp-nodejs-master\node_modules\@privacyresearch\libsignal-protocol-typescript\lib\session-builder.js:63:57)
    at Generator.next (<anonymous>)
    at fulfilled (D:\node\whatsapp-nodejs-master\node_modules\@privacyresearch\libsignal-protocol-typescript\lib\session-builder.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
TypeError: Cannot read property 'version' of null
TypeError: Cannot read property 'version' of null
D:\node\whatsapp-nodejs-master\node_modules\@privacyresearch\curve25519-typescript\lib\built\curveasm.js:136
                    throw ex;
                    ^

Error: abort(TypeError: Cannot read property 'version' of null). Build with -s ASSERTIONS=1 for more info.
    at process.abort (D:\node\whatsapp-nodejs-master\node_modules\@privacyresearch\curve25519-typescript\lib\built\curveasm.js:12903:19)
    at process.emit (events.js:376:20)
    at process.emit (domain.js:470:12)
    at process.emit.sharedData.processEmitHook.installedValue [as emit] (C:\Users\HUAWEI\AppData\Roaming\npm\node_modules\ts-node\node_modules\@cspotcode\source-map-support\source-map-support.js:613:40)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)

i am using latest version.

**Comment by resatkrlc** [comment]
Thank you!
